import type { Metadata } from "next";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/componet/ui/Navbar";
import Footer from "@/componet/ui/footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <h1 className="text-4xl  font-bold text-white">วะฮ่ะฮ่า</h1>
        <Navbar />
        {children}
        <Footer txt="© 2025 Lnwza007. All rights reserved."/>
      </body>
    </html>
  );
}
